config/routes.rb
Rails.application.routes.draw do
  resources :fotos_obras
  resources :obras
  get 'home/index'
  root 'home#index'
  devise_for :usuarios, controllers: {
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations',
    passwords: 'usuarios/passwords'
  }
  #devise_for :users
  #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fotos_obra.rb
class FotosObra < ApplicationRecord
    mount_uploader :foto, FotosObraUploader
    belongs_to :obra
end

app/controllers/fotos_obras_controller.rb
class FotosObrasController < ApplicationController
  before_action :set_fotos_obra, only: [:show, :edit, :update, :destroy]

  # GET /fotos_obras
  # GET /fotos_obras.json
  def index
    @fotos_obras = FotosObra.all
  end

  # GET /fotos_obras/1
  # GET /fotos_obras/1.json
  def show
    @fotos_obra = FotosObra.all.order('id desc')
  end

  # GET /fotos_obras/new
  def new
    @fotos_obra = FotosObra.new
  end

  # GET /fotos_obras/1/edit
  def edit
  end

  # POST /fotos_obras
  # POST /fotos_obras.json
  def create
    @fotos_obra = FotosObra.new(fotos_obra_params)

    respond_to do |format|
      if @fotos_obra.save
        format.html { redirect_to @fotos_obra, notice: 'Fotos obra was successfully created.' }
        format.json { render :show, status: :created, location: @fotos_obra }
      else
        format.html { render :new }
        format.json { render json: @fotos_obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fotos_obras/1
  # PATCH/PUT /fotos_obras/1.json
  def update
    respond_to do |format|
      if @fotos_obra.update(fotos_obra_params)
        format.html { redirect_to @fotos_obra, notice: 'Fotos obra was successfully updated.' }
        format.json { render :show, status: :ok, location: @fotos_obra }
      else
        format.html { render :edit }
        format.json { render json: @fotos_obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos_obras/1
  # DELETE /fotos_obras/1.json
  def destroy
    @fotos_obra.destroy
    respond_to do |format|
      format.html { redirect_to fotos_obras_url, notice: 'Fotos obra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fotos_obra
      @fotos_obra = FotosObra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fotos_obra_params
      params.require(:fotos_obra).permit(:obra_id, :foto)
    end
end

app/helpers/fotos_obras_helper.rb
module FotosObrasHelper
end

app/views/fotos_obras/_form.html.erb
<%= form_with(model: fotos_obra, local: true) do |form| %>
  <% if fotos_obra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fotos_obra.errors.count, "error") %> prohibited this fotos_obra from being saved:</h2>

      <ul>
      <% fotos_obra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :obra_id %>
    <%= form.number_field :obra_id %>
  </div>

  <div class="field">
    <%= form.label :foto %>
    <%= form.text_field :foto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fotos_obras/edit.html.erb
<h1>Editing Fotos Obra</h1>

<%= render 'form', fotos_obra: @fotos_obra %>

<%= link_to 'Show', @fotos_obra %> |
<%= link_to 'Back', fotos_obras_path %>

app/views/fotos_obras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fotos Obras</h1>

<table>
  <thead>
    <tr>
      <th>Obra</th>
      <th>Foto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fotos_obras.each do |fotos_obra| %>
      <tr>
        <td><%= fotos_obra.obra_id %></td>
        <td><%= fotos_obra.foto %></td>
        <td><%= link_to 'Show', fotos_obra %></td>
        <td><%= link_to 'Edit', edit_fotos_obra_path(fotos_obra) %></td>
        <td><%= link_to 'Destroy', fotos_obra, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fotos Obra', new_fotos_obra_path %>

app/views/fotos_obras/new.html.erb
<h1>New Fotos Obra</h1>

<%= render 'form', fotos_obra: @fotos_obra %>

<%= link_to 'Back', fotos_obras_path %>

app/views/fotos_obras/show.html.erb
<p id="notice"><%= notice %></p>

<% if @fotos_obra.exists? %>  
  <div class="row">
    <% @fotos_obra.each do |foto| %>

    <div class="col-md-3 col-xs-12 col-sm-6 fotos-column">      
        <div class="photo">
          <a href="<%= foto.foto_url() %>" class="photo-hover img-responsive" data-lightbox="my-fotos">
            <div class="mask"></div>
          </a>
          <div class="photo-img">
            <%= image_tag foto.foto_url() unless foto.foto.blank? %>
          </div>
        </div>      
    </div>
    <% end %>
  </div>
<% end %>


<%= link_to 'Edit', edit_fotos_obra_path(@fotos_obra) %> |
<%= link_to 'Back', fotos_obras_path %>