config/routes.rb
Rails.application.routes.draw do
  resources :fotos_obras
  resources :obras
  get 'home/index'
  root 'home#index'
  devise_for :usuarios, controllers: {
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations',
    passwords: 'usuarios/passwords'
  }
  #devise_for :users
  #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/obra.rb
class Obra < ApplicationRecord
    belongs_to :usuario
    has_many :fotos_obra
    accepts_nested_attributes_for :fotos_obra
end

app/controllers/obras_controller.rb
class ObrasController < ApplicationController
  before_action :set_obra, only: [:show, :edit, :update, :destroy]

  # GET /obras
  # GET /obras.json
  def index
    @obras = Obra.where("usuario_id = ?", current_usuario.id)
  end

  # GET /obras/1
  # GET /obras/1.json
  def show
  end

  # GET /obras/new
  def new
    @obra = Obra.new
    @fotos_obra = @obra.fotos_obra.build
  end

  # GET /obras/1/edit
  def edit
  end

  # POST /obras
  # POST /obras.json
  def create
    @obra = Obra.new(obra_params)
    @obra.usuario_id = current_usuario.id

    respond_to do |format|
      if @obra.save
        params[:fotos_obra]['foto'].each do |f|
          @fotos_obra = @obra.fotos_obra.create!(:foto => f,
            :obra_id => @obra.id)
        end

        format.html { redirect_to @obra, notice: 'Obra criada com sucesso' }
        format.json { render :show, status: :created, location: @obra }
      else
        format.html { render :new }
        format.json { render json: @obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /obras/1
  # PATCH/PUT /obras/1.json
  def update
    respond_to do |format|
      if @obra.update(obra_params)
        format.html { redirect_to @obra, notice: 'Obra atualizada com êxito.' }
        format.json { render :show, status: :ok, location: @obra }
      else
        format.html { render :edit }
        format.json { render json: @obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /obras/1
  # DELETE /obras/1.json
  def destroy
    @obra.destroy
    respond_to do |format|
      format.html { redirect_to obras_url, notice: 'Obra foi excluida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_obra
      @obra = Obra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def obra_params
      params.require(:obra).permit(:nome, :estilo_obra, :descricao, :preco, :quantidade, 
        fotos_obra_attributes: [:id, :obra_id, :foto])
    end
end

app/helpers/obras_helper.rb
module ObrasHelper
end

app/views/obras/_form.html.erb
<%= form_with(model: obra, local: true) do |form| %>
  <% if obra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(obra.errors.count, "error") %> prohibited this obra from being saved:</h2>

      <ul>
      <% obra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :estilo_obra %>
    <%= form.text_field :estilo_obra %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_area :descricao %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco %>
  </div>

  <div class="field">
    <%= form.label :quantidade %>
    <%= form.number_field :quantidade %>
  </div>

  <%= form.fields_for :fotos_obra do |f| %>
    <div class="field">
      <%= f.label :foto %><br>
      <%= f.file_field :foto, :multiple => true, name: "fotos_obra[foto][]" %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/obras/edit.html.erb
<h1>Editar uma Obra</h1>

<%= render 'form', obra: @obra %>

<%= link_to 'Mostrar', @obra %> |
<%= link_to 'Voltar', obras_path %>

app/views/obras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Obras</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Estilo obra</th>
      <th>Descrição</th>
      <th>Preço</th>
      <th>Quantidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @obras.each do |obra| %>
      <tr>
        <td><%= obra.nome %></td>
        <td><%= obra.estilo_obra %></td>
        <td><%= obra.descricao %></td>
        <td><%= obra.preco %></td>
        <td><%= obra.quantidade %></td>
        <td><%= link_to 'Mostrar', obra %></td>
        <td><%= link_to 'Editar', edit_obra_path(obra) %></td>
        <td><%= link_to 'Excluir', obra, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova obra', new_obra_path , class: "btn btn-primary" %>

app/views/obras/new.html.erb
<h1>Nova obra</h1>

<%= render 'form', obra: @obra %>

<%= link_to 'Voltar', obras_path %>

app/views/obras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @obra.nome %>
</p>

<p>
  <strong>Estilo obra:</strong>
  <%= @obra.estilo_obra %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @obra.descricao %>
</p>

<p>
  <strong>Preço:</strong>
  <%= @obra.preco %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @obra.quantidade %>
</p>

<%= link_to 'Editar', edit_obra_path(@obra) %> |
<%= link_to 'Voltar', obras_path %>